### ISSUE TITLE
【LP】ブラウザ確認および修正

### ISSUE THREAD

**Issue by kuruma-gs** [sikmi/politics#83]

**Comment by Ouchi44** [comment]
IE９
・3つのポイント内の丸ボタンをクリックに緑の部分が連動しない

IE8
・警告内の「どうする？」をホバーしても文章と背景が変わらない(最後の「詳しく聞く」も同様)
・問い合わせフォームが崩れている
・3つのポイント内の丸ボタンの画像が表示されず、文言のみが表示される
・3つのポイント内の丸ボタンをクリックに緑の部分が連動しない
![default](https://cloud.githubusercontent.com/assets/8385391/5103335/421fa8c6-701a-11e4-83f6-11a6668400c8.png)
